name: Kotlin CI with Gradle and Allure

on:
  workflow_dispatch:

jobs:
  build-test-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Set up latest Oracle JDK 22'
        uses: oracle-actions/setup-java@v1
        with:
            website: oracle.com
            release: 22

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests with Gradle
        run: ./gradlew clean test
        continue-on-error: true

      - name: Upload Allure results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: allure-results
          path: build/allure-results

      - name: Get Allure history
        uses: actions/checkout@v4.1.7
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GT }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
