name: Kotlin CI with Gradle and Allure

on:
  workflow_dispatch:

jobs:
  build-test-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests with Gradle
        run: ./gradlew test
        continue-on-error: true

      - name: Generate Allure Report
        run: ./gradlew allureReport
        if: always()

      - name: Upload Allure results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: allure-results
          path: build/allure-results

      - name: Get Allure history
        uses: actions/checkout@v4.1.7
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        env:
          PERSONAL_TOKEN: ${{ secrets.GH_TOKEN_PAGES }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

permissions:
  contents: write