name: CI with Docker Compose and Allure (Manual Trigger)

on:
  workflow_dispatch:

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run tests with Docker Compose
        run: |
          docker-compose up --build --abort-on-container-exit

      - name: Copy Allure results
        run: |
          docker cp $(docker-compose ps -q app):/app/build/allure-results ./allure-results

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_report: allure-report
          gh_pages: gh-pages
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN_PAGES }}
          publish_dir: ./allure-history

permissions:
  contents: write